"""S5 — the ``SPSS001`` migration checker, run through ``pssparser`` itself.

Each test runs the ``pssparser`` command's ``main`` in a temporary directory,
so the checker is found the way a user's run finds it: through the
``pssparser.extensions`` entry point of the installed package, with options
from a ``.pssparser.toml`` there. A failure to find it means the entry point in
``pyproject.toml`` is missing or the package isn't installed.

The last test runs the example on ``docs/usage/steps.md``, so the page can't
show output the checker doesn't give.
"""

from __future__ import annotations

import json
import pathlib
import re

import pytest

pytestmark = pytest.mark.unit

PAGE = pathlib.Path(__file__).resolve().parents[2] / "docs" / "usage" / "steps.md"

ENABLED = "[checker.sphinx-pss-steps]\nenabled = true\n"

#: Every form of comment, marked inside the comment with what the checker
#: should say about it: ``!`` for a report, ``-`` for silence.
SOURCE = """\
package drv {
    function void init_mac() {
        // Step: Reset the MAC                      !
        write_reg(0x0, 0x8000);
        // Step 2.1: A hand-numbered step           !
        //Step: No space after the slashes          !
        /* Step: A block comment                 ! */
        /*
         * Prose before the marker.
         *   Step: A marker inside a block comment  !
         */
        /// Step: Already a doc comment             -
        /** Step: Already a doc comment          - */
        //// Step: A rule of slashes is plain       -
        // step: The wrong case                     -
        // Steps are generated by the tool          -
        // Stepping through the counters            -
        // Note: Step: not at the start             -
        write_reg(0x4, 0x1);
    }

    function void write_reg(bit[32] offset, bit[32] value);
}
"""


def _run(tmp_path, monkeypatch, capsys, *args: str, config: str | None = None) -> tuple[int, str]:
    from pssparser.cli.app import main

    if config is not None:
        (tmp_path / ".pssparser.toml").write_text(config)
    monkeypatch.chdir(tmp_path)
    code = main(["--no-color", *args])
    captured = capsys.readouterr()
    return code, captured.out + captured.err


def _markers(tmp_path, monkeypatch, capsys, source: str, config: str | None) -> list[dict]:
    (tmp_path / "drv.pss").write_text(source)
    _, out = _run(tmp_path, monkeypatch, capsys, "--json", "drv.pss", config=config)
    return [d for d in json.loads(out)["diagnostics"] if d.get("code") == "SPSS001"]


def test_the_extension_is_registered(tmp_path, monkeypatch, capsys) -> None:
    _, out = _run(tmp_path, monkeypatch, capsys, "--list-extensions")
    assert re.search(r"^  sphinx-pss ", out, re.M)
    assert "checkers: sphinx-pss-steps" in out


def test_the_checker_declares_spss001_and_is_off_by_default(tmp_path, monkeypatch, capsys) -> None:
    _, out = _run(tmp_path, monkeypatch, capsys, "--describe-checker", "sphinx-pss-steps")
    assert re.search(r"SPSS001\s+\[warning\]", out)
    assert re.search(r"enabled\s+bool\s+default: false", out)


def test_the_checker_is_silent_by_default(tmp_path, monkeypatch, capsys) -> None:
    assert _markers(tmp_path, monkeypatch, capsys, SOURCE, config=None) == []


def test_enabled_it_reports_each_plain_marker_and_nothing_else(tmp_path, monkeypatch, capsys) -> None:
    lines = SOURCE.splitlines()
    expected = [(n, line.index("Step") + 1) for n, line in enumerate(lines, 1) if "!" in line]
    found = _markers(tmp_path, monkeypatch, capsys, SOURCE, config=ENABLED)
    assert [(d["line"], d["col"]) for d in found] == expected
    assert all(d["severity"] == "warning" for d in found)


def test_the_message_names_the_doc_comment_to_write(tmp_path, monkeypatch, capsys) -> None:
    source = "// Step: a\n/* Step: b */\n"
    found = _markers(tmp_path, monkeypatch, capsys, source, config=ENABLED)
    assert [d["message"] for d in found] == [
        "[SPSS001] plain comment looks like a step marker; write it as '/// Step: ...' to make it a step",
        "[SPSS001] plain block comment looks like a step marker; write it as '/** Step: ... */' to make it a step",
    ]


def test_two_block_comments_on_one_line_are_two_reports(tmp_path, monkeypatch, capsys) -> None:
    source = "/* Step: one */ /* Step: two */\n"
    found = _markers(tmp_path, monkeypatch, capsys, source, config=ENABLED)
    assert [(d["line"], d["col"], d["end_col"]) for d in found] == [(1, 4, 13), (1, 20, 29)]


def test_enabled_false_in_config_keeps_it_silent(tmp_path, monkeypatch, capsys) -> None:
    config = "[checker.sphinx-pss-steps]\nenabled = false\n"
    assert _markers(tmp_path, monkeypatch, capsys, SOURCE, config=config) == []


def _page_block(name: str) -> str:
    match = re.search(
        r"```\{code-block\} \w+\n:name: " + re.escape(name) + r"\n\n(.*?)```\n",
        PAGE.read_text(),
        re.DOTALL,
    )
    assert match, f"no block named {name} on {PAGE.name}"
    return match.group(1)


def test_the_page_example_gives_the_output_shown(tmp_path, monkeypatch, capsys) -> None:
    (tmp_path / "drv.pss").write_text(_page_block("step-migration-source"))
    command, _, shown = _page_block("step-migration-output").partition("\n")
    assert command == "$ pssparser drv.pss"
    code, out = _run(tmp_path, monkeypatch, capsys, "drv.pss", config=_page_block("step-migration-config"))
    assert code == 0
    assert out == shown
